IF(GPM_INCLUDES AND GPM_LIBRARIES)
  SET(GPM_FIND_QUIETLY TRUE)
ENDIF(GPM_INCLUDES AND GPM_LIBRARIES)

FIND_PATH(GPM_INCLUDES
          NAMES
          GPM/primitives.h
          PATHS
          /usr/local/include
          $ENV{HOME}/include)

FIND_LIBRARY(GPM_LIBRARIES 
             GPM
             PATHS
             /usr/local/lib
             $ENV{HOME}/lib)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(GPM DEFAULT_MSG
                                  GPM_INCLUDES GPM_LIBRARIES)

MARK_AS_ADVANCED(GPM_INCLUDES GPM_LIBRARIES)

IF(GPM_INCLUDES)
  # Export version information
  EXECUTE_PROCESS(COMMAND cat "${GPM_INCLUDES}/GPM/GPM_version.h" OUTPUT_VARIABLE GPM_HEADER)
  STRING(REGEX MATCH "GPM_VERSION_MAJOR ([0-9]+)" GPM_VERSION_MAJOR ${GPM_HEADER})
  STRING(REGEX REPLACE "GPM_VERSION_MAJOR ([0-9]+)" "\\1" GPM_VERSION_MAJOR "${GPM_VERSION_MAJOR}")
  STRING(REGEX MATCH "GPM_VERSION_MINOR ([0-9]+)" GPM_VERSION_MINOR ${GPM_HEADER})
  STRING(REGEX REPLACE "GPM_VERSION_MINOR ([0-9]+)" "\\1" GPM_VERSION_MINOR "${GPM_VERSION_MINOR}")
  STRING(REGEX MATCH "GPM_VERSION_PATCH ([0-9]+)" GPM_VERSION_PATCH ${GPM_HEADER})
  STRING(REGEX REPLACE "GPM_VERSION_PATCH ([0-9]+)" "\\1" GPM_VERSION_PATCH "${GPM_VERSION_PATCH}")
ENDIF(GPM_INCLUDES)
